name: GitHub Actions Updater

# Controls when the action will run.
on:
  schedule:
    - cron:  '0 11 * * 1' # runs at 11:00 UTC on Mondays
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.WORKFLOW_TOKEN }}
          pull_request_labels: automated pr
