name: Test Image Build

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      commit:
        required: true
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Login to DockerHub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set image name
      id: setimagename
      env:
        REPOSITORY: ${{ inputs.repository }}
        COMMIT: ${{ inputs.commit }}
      run: |
          echo "Image name: $REPOSITORY:$COMMIT"
          echo "imagename=$REPOSITORY:$COMMIT" >> $GITHUB_OUTPUT

    - name: Build the image
      id: buildimage
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./
        file: ./Dockerfile
        push: false
        tags: ${{ steps.setimagename.outputs.imagename }}
